#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
#
Name     : perl-Test-LeakTrace
Version  : 0.17
Release  : 35
URL      : https://cpan.metacpan.org/authors/id/L/LE/LEEJO/Test-LeakTrace-0.17.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/L/LE/LEEJO/Test-LeakTrace-0.17.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libt/libtest-leaktrace-perl/libtest-leaktrace-perl_0.16-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Test-LeakTrace-license = %{version}-%{release}
Requires: perl-Test-LeakTrace-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This is Perl module Test::LeakTrace.
INSTALLATION
Test::LeakTrace installation is straightforward. If your CPAN shell is set up,
you should just be able to do

%package dev
Summary: dev components for the perl-Test-LeakTrace package.
Group: Development
Provides: perl-Test-LeakTrace-devel = %{version}-%{release}
Requires: perl-Test-LeakTrace = %{version}-%{release}

%description dev
dev components for the perl-Test-LeakTrace package.


%package license
Summary: license components for the perl-Test-LeakTrace package.
Group: Default

%description license
license components for the perl-Test-LeakTrace package.


%package perl
Summary: perl components for the perl-Test-LeakTrace package.
Group: Default
Requires: perl-Test-LeakTrace = %{version}-%{release}

%description perl
perl components for the perl-Test-LeakTrace package.


%prep
%setup -q -n Test-LeakTrace-0.17
cd %{_builddir}
tar xf %{_sourcedir}/libtest-leaktrace-perl_0.16-1.debian.tar.xz
cd %{_builddir}/Test-LeakTrace-0.17
mkdir -p deblicense/
cp -r %{_builddir}/debian/* %{_builddir}/Test-LeakTrace-0.17/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Test-LeakTrace
cp %{_builddir}/debian/copyright %{buildroot}/usr/share/package-licenses/perl-Test-LeakTrace/ac6050b603c4d8a452e10f290eef12636f01755e || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Test::LeakTrace.3
/usr/share/man/man3/Test::LeakTrace::JA.3
/usr/share/man/man3/Test::LeakTrace::Script.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Test-LeakTrace/ac6050b603c4d8a452e10f290eef12636f01755e

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
